### ISSUE TITLE
pdb70 contains invalid HMM / A3M entries, crashing hhblits

### ISSUE THREAD

**Issue by sseemayer** [soedinglab/hhdatabase_cif70#3]
Thanks so much for maintaining this and the regular updates!

When using [pdb70_from_mmcif_201130](http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/pdb70_from_mmcif_201130.tar.gz), we had some automatic pipelines break on a hhblits run with an error message:

```
$ hhblits -i uniclust30.ss.a3m -d /path/to/pdb70 pdb.a3m -o pdb.hhr
- 10:14:57.125 INFO: Searching 76603 column state sequences.
- 10:14:57.197 INFO: uniclust30.ss.a3m is in A2M, A3M or FASTA format
- 10:15:05.558 INFO: Iteration 1
- 10:15:06.547 INFO: Prefiltering database
- 10:15:08.590 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 4896
- 10:15:08.677 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 1055
- 10:15:08.677 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 1055
- 10:15:08.677 INFO: Scoring 1055 HMMs using HMM-HMM Viterbi alignment
- 10:15:08.733 INFO: Alternative alignment: 0
- 10:15:08.820 ERROR: In /path/to/hh-suite-3.3.0/src/hhdatabase.cpp:443: getTemplateHMM:
- 10:15:08.820 ERROR: 	Unrecognized HMM file format in '5L1D_A'.
- 10:15:08.820 ERROR: 	Context:
'
- 10:15:08.820 ERROR: 
- 10:15:08.820 ERROR: '
```

I have traced this back to empty entries in the pdb70_hhm database:

```
[...]
5L1A_A	151873163	12909
5L1B_D	2611681429	135255
5L1D_A	2883842330	1
5L1D_F	367161477	1
5L1M_A	487738052	28709
5L1N_B	1937736007	77145
5L1Q_A	1707377073	1
5L1R_A	1707377074	66422
5L1X_G	77767904	1
5L1X_I	77767905	1
5L1X_L	1629961730	47928
[...]
```

The same entries did not occur in [version 201113](http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/pdb70_from_mmcif_201113.tar.gz).

I have worked around the issue for now by downgrading to the older pdb70 version.

**Comment by sseemayer** [comment]
Also, best wishes to the team from Ludwigshafen <3

**Comment by milot-mirdita** [comment]
Thanks for the bug report. The new cluster thought I am fork bombing it since it's running 256x the addss.pl script which calls a lot of other programs. I think I fixed the issue. I am rebuilding the database to check.

**Comment by milot-mirdita** [comment]
I reuploaded the latest PDB70 from before the cluster migration:
http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/old-releases/pdb70_from_mmcif_200916.tar.gz

Might still take a while to stabilize this.

**Comment by milot-mirdita** [comment]
The latest version doesn't contain any 0-byte entries anymore. Thanks again for reporting the issue.
